.PHONY: all clean
cc:=~/NDK/android-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
cpp:=~/NDK/android-ndk-r24/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
#cc:=gcc
#cpp:=g++
all:
	#$(cpp) -shared -fpic -std=c++11 -o libmyperfetto.so perfetto.cc
	$(cpp) -c -g -std=c++11 -fno-emulated-tls -o  test_no_instrument.o test_no_instrument.cc
	$(cpp) -o test_no_instrument test_no_instrument.o -L. -lmyperfetto -llog -pthread

clean:
	rm -rf test_no_instrument *.o a.out perfetto.o libmyperfetto.so
