LOCAL_PATH:=$(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:=Test
LOCAL_SRC_FILES:=test.c
LOCAL_EXPORT_C_INCLUDES:=$(LOCAL_PATH)
# LOCAL_EXPORT_LDLIBS:= -llog

# include $(BUILD_STATIC_LIBRARY)
include $(BUILD_SHARED_LIBRARY)
